#!/usr/bin/env bash

FZF_DEFAULT_OPTS="--layout=reverse --border=top --border-label=\"Kill session\" --border-label-pos=1 --no-info --no-scrollbar"
# Flexoki theme
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
    --color=fg:#878580,bg:#100F0F,hl:#CE5D97
    --color=fg+:#878580,bg+:#1C1B1A,hl+:#CE5D97
    --color=border:#403E3C,header:#FFFCF0,gutter:#100F0F
    --color=spinner:#24837B,info:#24837B,separator:#1C1B1A
    --color=pointer:#AD8301,marker:#A02F6F,prompt:#AD8301"

for s in $(tmux list-sessions -F \#S | fzf); do
    tmux kill-session -t "$s"
done
