#!/usr/bin/env bash
# Original: https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer

if [[ $# -eq 1 ]]; then
    selected=$1
else
    FZF_DEFAULT_OPTS="--layout=reverse --border=top --border-label=\"Go to session\" --border-label-pos=1 --no-info --no-scrollbar"
    # Flexoki theme
     export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
        --color=fg:#878580,bg:#100F0F,hl:#CE5D97
        --color=fg+:#878580,bg+:#1C1B1A,hl+:#CE5D97
        --color=border:#403E3C,header:#FFFCF0,gutter:#100F0F
        --color=spinner:#24837B,info:#24837B,separator:#1C1B1A
        --color=pointer:#AD8301,marker:#A02F6F,prompt:#AD8301"

    existing_tmux_sessions=$(tmux list-sessions -F \#S)
    dotfiles="$HOME/.dotfiles"
    repos=$(find ~/develop ~/foss ~/work -mindepth 1 -maxdepth 1 -type d 2> /dev/null)

    # We need to preserve linebreaks between command outputs
    selected=$(printf '%s\n%s\n%s\n' "$existing_tmux_sessions" "$dotfiles" "$repos" | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
fi

tmux switch-client -t "$selected_name"
